### ISSUE TITLE
Dictionary keys and order

### ISSUE THREAD

**Issue by jonathanrobie** [Copenhagen-Alliance/versification-specification#2]
We are using dictionary keys to enumerate books in `maxVerses` and other places.  As the JSON spec tells use:

> An object is an unordered set of name/value pairs.

Do we need a way to specify the order of book?

**Comment by jonathanrobie** [comment]
We closed this yesterday, saying the order of books is out of scope and would be specified elsewhere.

**Comment by chris-morgan** [comment]
If it’s out of scope here, I’m curious where it’s supposed to be *in* scope. I’m a newcomer to this space, and the one work I’ve looked at in any detail so far, engWEBBE from DBL, uses non-sequential book file names (GEN.usx, EXO.usx, *&c.*) and has no other relevant metadata, so that its versification.vrs is the only thing I can see that could possibly specify book order. Losing that property would make this rather unsuitable as a replacement.

(Aside: its versification.vrs doesn’t entirely match the work—its text contains PSA 151, but its versification only goes up to PSA 150 and PS2 1 and has no mapping around PSA 150 or PS2 1. If it doesn’t even necessarily match, I honestly can’t see *any* value in tracking the number of chapters and verses in books in versifications, for any kind of *publication*—only for tooling assistance during editing. The mapping is the part that has actual value.)

**Comment by jonathanrobie** [comment]
Book order is different in different canons.  The same text may be used to print, say, a Protestant Bible, a Catholic Bible, an Orthodox Bible, each in different book orders.    The same Old Testament books translated from a Hebrew Old Testament might be printed in either traditional Jewish order or traditional Protestant order.  So there simply isn't one set of book orders, you have to look to canons for that.  And that means that hard coding book order into the names of books only works if you will only ever use that translation in one canonical order.  For most translations, that's probably true, but it doesn't work for all.

engWEBBE came from ebible.org - https://ebible.org/ - they are the right people to talk to about any errors in their versification.vrs.

**Comment by jonathanrobie** [comment]
I'm not sure if there is an issue for our versification spec to resolve here. Are you suggesting that we add book order?  I would prefer to leave that up to the canon.

**Comment by jonathanrobie** [comment]
If you are printing the same text in both English and Jewish order, odds are that you are using Hebrew chapter numbers, which are close to the Protestant chapter numbers in general.    If you are printing both an Orthodox and a Protestant translation from the same source, odds are good that the Protestant version will include something called an "Apocrypha" and the Orthodox version will put it all in one place - after deciding whether or not to put that text in separate books as a Protestant would. 

This is a real requirement we have been asked to meet by people who do this kind of thing.

I can't really speak specifically to eBible's engWEBBE, the version on DBL was uploaded by eBible, so I suggest you talk to them.

There are various ways we could add support for book orders.  Often, the main place this comes up in software is in the dialog used to open up a book, and software tends to use the same order in those dialogs, even if the Bibles they use might be printed in a different order.  The Software might, for instance, take a modern Protestant view of book order, even when looking at the Septuagint.   But a printer would normally print the Septuagint in traditional Greek order.  And that same printer probably has to think carefully when preparing an Ethiopian Orthodox Bible for print.

I could imagine adding support for book order.  But we would have to think all of this through carefully.  I suspect adding a section that supports one or more book orders would make sense.

**Comment by jonathanrobie** [comment]
> So yeah, I was largely just assuming that the order of books in the versification file was significant because (a) it matches what I’d expect, and (b) I can’t see what else might be conveying the information.

In a Python dictionary, the order of keys is not significant.  If we want to specify order, we can't do it this way.

**Comment by RobH123** [comment]
That's no longer correct. From 
https://docs.python.org/3/library/stdtypes.html?highlight=dict#dict

    Changed in version 3.7: Dictionary order is guaranteed to be
    insertion order.

Robert.

**Comment by chris-morgan** [comment]
I know that JSON objects should not be treated as order-significant. What I was suggesting was simply that the current schema had lost something that I thought *must* have been significant about the .vrs format.

On reflection and review, though, in files like org.vrs and eng.vrs, deuterocanonical books appear after the New Testament books, so their order is clearly *not* indicating desired book order, and I was barking up the wrong tree the whole time, and I’m left not knowing how book order is supposed to be signalled.

You speak of “leaving it up to the canon”: where is this canon, how does a work identify what canon it uses? (And in the case of DBL resources, is this the USX_1/USX_2/*&c.* directories? Are those hard-coded values or something else?)

I’d presumed that “canons” and “versifications” were essentially merged concepts, like they are in SWORD.

(I shouldn’t have brought up the defects of engWEBBE’s .vrs file. It was meant to be an aside uncommented-on.)

**Comment by jonathanrobie** [comment]
> That's no longer correct. From https://docs.python.org/3/library/stdtypes.html?highlight=dict#dict Changed in version 3.7: Dictionary order is guaranteed to be insertion order.

True.

But the semantics of JSON are defined by JSON, which has to work in other languages as well.
