### ISSUE TITLE
maxVerses with partial verses like 24a, 24b

### ISSUE THREAD

**Issue by jonathanrobie** [Copenhagen-Alliance/versification-specification#3]
If the last verse in a chapter were a partial verse like 24a, should the maxVerses value be 24 or 24a?

**Comment by jonathanrobie** [comment]
@foolrunning can you please tell us what Paratext does in this case?  (if it ever occurs?)

**Comment by FoolRunning** [comment]
In Paratext, the maximum verse would be "24" and there would be a verse segment line like the following to clarify:
EXO 28:24,-,a

**Comment by jonathanrobie** [comment]
Thanks.  I think that matches what I am doing.
